[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.2"

# The title and description fields are primarily for displaying extension info in UI
title = "Rhino Compute for Omniverse"
description="Omniverse intergration with a rhino.compute server"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "../../README.md"

# URL of the extension source repository.
repository = "https://github.com/rcervellione-nv/omni.rhinocompute"

# One of categories for UI.
category = "Utility"

# Keywords for the extension
keywords = ["kit", "Rhino", "Compute"]

# Icon to show in the extension manager
icon = "data/computeTerminal.png"

# Preview to show in the extension manager
preview_image = "data/CreateAndCompute.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "cerver.util.rhinocompute"
